const tours = new Map()

tours.set('1', { location: 'Tampa, FL', date: 'May 26', price: 49.0 })
tours.set('2', { location: 'Orlando, FL', date: 'May 28', price: 49.0 })
tours.set('3', { location: 'Tallahassee, FL', date: 'May 29', price: 49.0 })
tours.set('4', { location: 'Atlanta, GA', date: 'May 30', price: 49.0 })
tours.set('5', { location: 'Montgomery, AL', date: 'June 1', price: 49.0 })
tours.set('6', { location: 'Birmingham, AL', date: 'June 2', price: 49.0 })
tours.set('7', { location: 'Jackson, MS', date: 'June 4', price: 49.0 })
tours.set('8', { location: 'Baton Rouge, LA', date: 'June 6', price: 49.0 })
tours.set('9', { location: 'Little Rock, AK', date: 'June 7', price: 49.0 })
tours.set('10', { location: 'Austin, TX', date: 'June 8', price: 49.0 })
tours.set('11', { location: 'Houston, TX', date: 'June 9', price: 49.0 })
tours.set('12', { location: 'El Paso, TX', date: 'June 11', price: 49.0 })
tours.set('13', { location: 'Tulsa, OK', date: 'June 13', price: 49.0 })
tours.set('14', { location: 'Santa Fe, NM', date: 'June 14', price: 49.0 })
tours.set('15', { location: 'Phoenix, AZ', date: 'June 16', price: 49.0 })
tours.set('16', { location: 'Sedona, AZ', date: 'June 17', price: 49.0 })
tours.set('17', { location: 'Los Angeles, CA', date: 'June 19', price: 49.0 })
tours.set('18', { location: 'San Francisco, CA', date: 'June 20', price: 49.0 })
tours.set('19', { location: 'Las Vegas, NV', date: 'June 22', price: 49.0 })
tours.set('20', { location: 'Salt Lake City, UT', date: 'June 23', price: 49.0 })
tours.set('21', { location: 'Denver, CO', date: 'June 24', price: 49.0 })
tours.set('22', { location: 'Wichita, KS', date: 'June 25', price: 49.0 })
tours.set('23', { location: 'Kansas City, MO', date: 'June 26', price: 49.0 })
tours.set('24', { location: 'Columbus, OH', date: 'June 28', price: 49.0 })
tours.set('25', { location: 'Philadelphia, PA', date: 'June 29', price: 49.0 })
tours.set('26', { location: 'Pittsburgh, PA', date: 'June 30', price: 49.0 })
tours.set('27', { location: 'Richmond, VA', date: 'July 1', price: 49.0 })
tours.set('28', { location: 'Charleston, SC', date: 'July 2', price: 49.0 })
tours.set('29', { location: 'New York City, NY', date: 'July 5', price: 49.0 })
tours.set('30', { location: 'Manhattan, NY', date: 'July 6', price: 49.0 })
tours.set('31', { location: 'Atlantic City, NJ', date: 'July 7', price: 49.0 })
tours.set('32', { location: 'Hartford, CT', date: 'July 9', price: 49.0 })
tours.set('33', { location: 'Boston, MA', date: 'July 10', price: 49.0 })
tours.set('34', { location: 'Detroit, MI', date: 'July 12', price: 49.0 })
tours.set('35', { location: 'Madison, WI', date: 'July 13', price: 49.0 })
tours.set('36', { location: 'St. Paul, MN', date: 'July 14', price: 49.0 })
tours.set('37', { location: 'Iowa City, IA', date: 'July 16', price: 49.0 })
tours.set('38', { location: 'Pierre, SD', date: 'July 17', price: 49.0 })
tours.set('39', { location: 'Bismarck, ND', date: 'July 19', price: 49.0 })
tours.set('40', { location: 'Billings, MT', date: 'July 20', price: 49.0 })
tours.set('41', { location: 'Boise, ID', date: 'July 22', price: 49.0 })
tours.set('42', { location: 'Salem, OR', date: 'July 23', price: 49.0 })
tours.set('43', { location: 'Seattle, WA', date: 'July 24', price: 49.0 })

export { tours }
